databases:
  - name: timeout-prod
    plan: free

services:
  - type: web
    name: timeout-app
    env: node
    plan: free
    buildCommand: npm ci --production=false && npm run build && npm prune --production
    startCommand: npx prisma migrate deploy && npm run start
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: timeout-prod
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: NODE_ENV #required so NODE_ENV is set in build env
        value: production
